server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qqjianyue/test.git
          username: qqjianyue
          password: "QQjianyue12#"